name: scrape

on:
  schedule:
    - cron: '0 23 * * 1-5'  # 23:00 UTC -> 20:00 Sao Paulo, Brazil
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Copied from:
      #   https://github.com/actions/checkout/issues/172#issuecomment-689169138
      - name: Sparse checkout
        shell: bash
        run: |
          REPO="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git clone --filter=blob:none --no-checkout --depth 1  --sparse $REPO .
          git sparse-checkout init --cone
          git sparse-checkout add "data"
          git checkout
      - run: |
          mkdir -pv data
          make today
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Inserting intraday
